In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [90]:
#From 28 dec 
data = pd.read_csv('hi.csv')

In [92]:
X = data.drop('corona',axis=1)
y = data['corona']

In [93]:
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.2,shuffle=False)

In [94]:
X_train = np.array(X_train)
X_train = X_train.reshape((1,-1))
y_train = np.array(y_train)
y_train = y_train.reshape((1,-1))
X_test = np.array(X_test)
X_test = X_test.reshape((1,-1))
y_test = np.array(y_test)
y_test = y_test.reshape((1,-1))

In [95]:
X_train

array([[ 1,  4,  2,  4,  3,  4,  4,  4,  5,  4,  6,  4,  7,  4,  8,  4,
         9,  4, 10,  5, 11,  5, 12,  5, 13,  5, 14,  5, 15,  5, 16,  5]],
      dtype=int64)

In [96]:
li = LinearRegression()
li.fit(X_train, y_train)

LinearRegression()

In [97]:
li.score(X_test,y_test)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 32 is different from 16)

In [98]:
pred = li.predict(X_test)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 32 is different from 16)

[17. 18. 19. 20.]


In [84]:
X_test

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160]], dtype=int64)